### ISSUE TITLE
ref warnings on stateless styled components

### ISSUE THREAD

**Issue by JulianKingman** [shoutem/theme#19]
I'm getting ref warnings on my styled stateless components, like so:
![screen shot 2017-04-18 at 8 17 36 am](https://cloud.githubusercontent.com/assets/1566400/25130253/874be454-240f-11e7-8c92-9987e25b1313.png)
I think it has to do with the order of `ref` and `addedProps`, but I'm not sure. I tried it with the `withRef` option set to true and false, neither seemed to help.
Ideas? It's just kind of annoying. I'm on the latest versions of everything (rn 0.43.3, @shoutem/theme 0.9.0)

**Comment by JulianKingman** [comment]
@Vladimir-Vdovic are you able to merge the PR? @MrBr seems to have gone MIA.

**Comment by zrumenjak** [comment]
@JulianKingman thanks for the PR, the fix for this is merged, and it is available in v0.10.0
