### ISSUE TITLE
There is some error with react-native@0.45

### ISSUE THREAD

**Issue by iwlog** [shoutem/theme#23]
There is some error with react-native@0.45

**Comment by Vladimir-Vdovic** [comment]
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Going to mark this issue as a duplicate of https://github.com/shoutem/ui/issues/241.

Please reference mentioned issue for future updates.
