### ISSUE TITLE
PropTypes should be imported from 'prop-types'

### ISSUE THREAD

**Issue by edcs** [shoutem/theme#30]
I can see that `PropTypes` are being imported from `'prop-types'` in develop, but in the latest release they're still being imported from `'react'`. This is throwing errors all over the place in my app! Please could you tag a new which includes these changes?

**Comment by tquiroga** [comment]
+1

**Comment by sagark1510** [comment]
+1

**Comment by edcs** [comment]
Think this project has been abandoned - I've since moved over to this:

https://github.com/robinpowered/glamorous-native

**Comment by sparameshwar** [comment]
Is there really no support for shoutem themes any more? The latest version simply does not work with recent RN versions. Should I be exploring alternate options as edcs has propose above?

**Comment by Vladimir-Vdovic** [comment]
Hey guys, we just now published @shoutem/theme version 0.11.0, which is compatible with the latest React Native version. @shoutem/animation version 0.12.0 is also live. We're still working on the @shoutem/ui, but you can expect it later today or tomorrow.

For more info about our renewed efforts to maintain the UI toolkit (Theme, Animation and UI packages), take a look at [this comment](https://github.com/shoutem/ui/pull/314#issuecomment-348678537).

**Comment by sagark1510** [comment]
Awesome.
