### ISSUE TITLE
Styling based on multiple styleNames

### ISSUE THREAD

**Issue by himanshu-satija** [shoutem/theme#5]
Hey there, nice work. It's a very useful library.

I want to know if it's possible to do apply different styles to a component according to combination of styleNames. For example, I want different styles for a button in these cases:
```jsx
<Button bordered />
<Button danger />
<Button bordered danger />
```

This is what I would do considering CSS kind of styling:
```js
'components.Button': {
  '.bordered': {
    borderWidth: 1,
    borderColor: 'blue',
    backgroundColor: 'transparent',
    'components.Text': {
      color: 'blue',
    },
  },
  '.danger': {
    borderWidth: 0,
    backgroundColor: 'red',
    'components.Text': {
      color: 'white',
    },
  },
  '.bordered.danger': {
    borderWidth: 1,
    borderColor: 'red',
    backgroundColor: 'transparent',
    'components.Text': {
      color: 'red',
    },
  },
}
  
```

**Comment by MrBr** [comment]
It is possible but you have to set wanted styles differently. In general you have to apply styles with `styleNames` property.

```
<Button styleNames="bordered" />
<Button styleNames="bordered danger" />
```

Unfortunately you can not "stack" styles to defined conditional style `.bordered.danger`. However you can nest style to achieve same effect.

```
'.danger': {
    '.bordered': {
        ...'.bordered.danger'
    },
    borderWidth: 0,
    backgroundColor: 'red',
    'components.Text': {
      color: 'white',
    },
},
```
