### ISSUE TITLE
build crash Parallax.js doesnt exist

### ISSUE THREAD

**Issue by ajonno** [shoutem/theme#6]
Wanted to test this today, created new project: 
```
  "dependencies": {
    "@shoutem/theme": "^0.8.7",
    "@shoutem/ui": "^0.9.1",
    "react": "15.4.1",
    "react-native": "0.38.0"
```

threw this build error on ios:
![image](https://cloud.githubusercontent.com/assets/3005269/20651980/af2dfef6-b544-11e6-956a-c8ef6c192c4b.png)

**Comment by tenodi** [comment]
Hey @ajonno, thanks for submitting this issue! We had some problems with [@shoutem/animation](https://github.com/shoutem/animation) library, which are fixed in [#8](https://github.com/shoutem/animation/pull/8).

You can try using it now, it should work.
