### ISSUE TITLE
Explain how to pass props, or make it possible, with connectStyle

### ISSUE THREAD

**Issue by JulianKingman** [shoutem/theme#9]
So I'm using `connectStyle` all over the place, which is cool (I like the idea of it), but I'm having trouble with props not being passed through. For example I wrap a container like so:

````javascript
export default connectStyle('project.component.ProjectTabs', styles)(ProjectTabs);
````

and then when I do this elsewhere:
````javascript
render(){
  <ProjectTabs someProperty="somevalue"/>
}
````

someProperty is not passed along to ProjectTabs (because, I suspect, the secret style component actually receives them, and isn't passing them along). Can you confirm this, or tell me what the proper way to pass the props through is, if you have one?

**Comment by MrBr** [comment]
This is unlikely, `connectStyle` passes all props to wrapped component.

Have you resolved this issue?

If not, can you please provide both `ProjectTab` definition file and some file where you use it.

**Comment by JulianKingman** [comment]
Yes, it's resolved. I don't remember which prop wasn't getting passed, but I think it was a problem with the particular component I was using, and not connectStyle. I've also had issues with static properties in components, but that's a separate issue (that I resolved with this: https://github.com/mridgway/hoist-non-react-statics)
